POST_STREAM = "post_stream"
REPLY_RANKING_RECOVERY = "reply_ranking_recovery"
TOPIC_UNIFIED_POSTS = "content-understanding-realtime-unified-posts"
TOPIC_REPLY_RANKING_RECOVERY = "reply_ranking_annotation_recovery_v2"
GEMMA_2 = "oai-gemma4-26b-2"
